name: Execute SSH commmands on remote server
on:
  push:
    branches:
    - 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: ls